
trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

variables:
  isGitHubTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]

stages:
  - stage: Build
    jobs: 
    - job: package
      condition: ne(variables['isGitHubTag'], 'true')
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - checkout: self
      -template: templates/prepare-maven.yml
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean package verify'
          options: '-DperformRelease=true'
      - script: |
          ls -al $(Build.SourcesDirectory)
          ls -al $(Build.ArtifactStagingDirectory)
    - job: deploy_snapshot
      dependsOn: package
      condition: ne(variables['isGitHubTag'], 'true')
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - checkout: none
      - script: |
          ls -al $(Build.SourcesDirectory)



